# Generated by Django 5.2.5 on 2025-08-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_table_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
