# Generated by Django 5.2.5 on 2025-08-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_siteconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
