# Generated by Django 5.2.5 on 2025-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('VEG', 'Veg'), ('NONVEG', 'Non-Veg'), ('OTHER', 'Other')], default='VEG', max_length=10),
        ),
    ]
