# Generated by Django 5.1.3 on 2025-08-14 07:29

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_category_is_active_menuitem_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='config',
            name='beep_audio',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.upload_beep_path),
        ),
        migrations.AddField(
            model_name='config',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.upload_favicon_path),
        ),
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.upload_logo_path),
        ),
        migrations.AddField(
            model_name='config',
            name='site_name',
            field=models.CharField(default='QR Order', max_length=120),
        ),
        migrations.AlterField(
            model_name='config',
            name='server_ip',
            field=models.CharField(help_text='Domain or public IP for QR links', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(default='TEMP', max_length=20),
        ),
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Configuration',
                'verbose_name_plural': 'License Configuration',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='config',
            name='restaurant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.restaurant'),
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='orders.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'code')},
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
